name: waygo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1-beta

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_baidu_mapapi_base: ^3.9.5
  flutter_baidu_mapapi_map: ^3.9.5
  flutter_baidu_mapapi_utils: ^3.9.5
  flutter_baidu_mapapi_search: ^3.9.5
  flutter_bmflocation: ^3.8.0

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  logger: ^2.6.1
  dio: ^5.8.0+1
  flutter_smart_dialog: ^4.9.8+9
  carousel_slider: ^5.1.1
  audioplayers: ^6.5.0
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  json_serializable: ^6.9.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map_style/

flutter_native_splash:
  color: "#ffffff"
  branding: assets/branding.png
  image: assets/splash.png
  android_12:
    branding: assets/branding.png
    image: assets/splash.png
